# frozen_string_literal: true

tap 'homebrew/cask-fonts'
cask 'font-caskaydia-cove-nerd-font'
cask 'font-fira-code-nerd-font'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-inconsolata-go-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
