#!/usr/bin/ruby
# frozen_string_literal: true

# Usage: dotf zshell
# Summary: Installs oh-my-zshell
# Help: It just clones the oh-my-zshell repo and sets some default configuration

puts '---------------------------------------------------------------------------------'
puts 'Installing zshell and oh my zsh'
puts '---------------------------------------------------------------------------------'

require "#{ENV['_DOTF_ROOT']}/share/dotf/file_rsync"
oh_my_zshell_install_script = 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
powerlevel_install_script = 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k'

puts 'Do you want me to install zsh as the default shell? This will run the script:'
puts "'#{oh_my_zshell_install_script}'"
puts '(y/n)'
unless gets.chomp =~ /^[Yy]/
  puts 'Aborting...'
  exit 2
end

puts
puts "Installing oh-my-zsh..."
system "#{oh_my_zshell_install_script}"

if File.exist? '~/.zshrc'
  puts 'Found and existing zshrc file. Making a backup called .zshrc.orig'
  FileUtils.cp('~/.zshrc', '~/.zshrc.orig')
end

puts 'Installing Powerlevel theme for zsh...'
system "#{powerlevel_install_script}#"


result = system 'chsh -s /bin/zsh'
exit result unless result == 0

puts 'All operations completed. Open a new shell to see the changes'
exit 0
