#!/usr/bin/ruby

# Usage: dotf fonts
# Summary: Install special fonts used in some oh-my-shell skins
# Help: Installed in the user's library folder.

require "#{ENV['_DOTF_ROOT']}/share/dotf/file_rsync"

puts "---------------------------------------------------------------------------------"
puts 'Copying files to user font folder'
puts "---------------------------------------------------------------------------------"


FileRsync.new('./fonts/', "#{ENV['HOME']}/Library/Fonts/").rsync_files

exit 0
    