#!/usr/bin/env ruby
# frozen_string_literal: true

# Usage: dotf apps
# Summary: Installs homebrew cask and install several apps
# Help: This will install homebrew cask and the packages defined in the
# file configuration/apps/Brewfile

require "#{ENV['_DOTF_ROOT']}/share/dotf/homebrew"

brewfile_filepath = "#{ENV['_DOTF_ROOT']}/../configuration/apps/Brewfile"

bundle_homebrew(brewfile_filepath)
