#!/usr/bin/ruby

# Usage: dotf config-files
# Summary: Copies shell config files to the proper places to set the defaults
# Help: Sets my default zshell config, paths, etc.

require "#{ENV['_DOTF_ROOT']}/share/dotf/file_rsync"



puts "---------------------------------------------------------------------------------"
puts 'Copy configuration files in home folder'
puts "---------------------------------------------------------------------------------"

puts "Some files in your home directory could be overwritten. Continue? (y/n)"
unless gets.chomp =~ /^[Yy]/
    puts 'Aborting...'
    exit 2
end

puts
puts "Updating configuration files in directory #{ENV['HOME']}/.config/shell"
puts "---------------------------------------------------------------------------------"
FileRsync.new("#{ENV["_DOTF_ROOT"]}/share/configuration_files/config", "~/.config/shell").rsync_files

puts
puts "Updating dotfiles in directory #{ENV['HOME']}"
puts "---------------------------------------------------------------------------------"
FileRsync.new("#{ENV["_DOTF_ROOT"]}/share/configuration_filesroot/", "~/").rsync_files


exit 0