#!/usr/bin/ruby

require "#{ENV['_DOTF_ROOT']}/share/dotf/file_rsync"

puts "---------------------------------------------------------------------------------"
puts 'Copy configuration files in home folder'
puts "---------------------------------------------------------------------------------"

puts "Some files in your home directory could be overwritten. Continue? (y/n)"
unless gets.chomp =~ /^[Yy]/
    puts 'Aborting...'
    exit 2
end

puts
puts "Updating configuration files in directory #{ENV['HOME']}/.confiles"
puts "---------------------------------------------------------------------------------"
FileRsync.new("./.confiles", "~/").rsync_files

puts
puts "Updating dotfiles in directory #{ENV['HOME']}"
puts "---------------------------------------------------------------------------------"
FileRsync.new("./.dotfiles/", "~/").rsync_files

puts 
puts "Updating #{ENV['HOME']}/.zshrc file"
puts "---------------------------------------------------------------------------------"
FileRsync.new(".zshrc", "~/.zshrc").rsync_files

exit 0